const actions = {
  CREATE_FILE: [
    "create",
    "produce",
    "generate",
    "develop",
    "construct",
    "build",
    "establish",
    "form",
    "invent",
    "design",
    "compose",
    "originate",
    "initiate",
    "fabricate",
    "found",
    "shape",
    "make",
    "instantiate",
    "initialize",
    "launch",
  ],
  DELETE_FILE: [
    "delete",
    "demolish",
    "obliterate",
    "ruin",
    "annihilate",
    "devastate",
    "wreck",
    "eradicate",
    "exterminate",
    "terminate",
    "shatter",
    "disintegrate",
    "extinguish",
    "decimate",
    "dismantle",
    "remove",
    "erase",
    "discard",
    "unlink",
    "rm",
  ],
  RENAME_FILE: [
    "rename",
    "change",
    "relabel",
    "retitle",
    "rechristen",
    "retag",
    "rebrand",
  ],
  ADD_TO_FILE: [
    "add",
    "write",
    "append",
    "attach",
    "include",
    "insert",
    "combine",
    "join",
    "augment",
    "enrich",
    "supplement",
    "update",
    "extend",
    "enhance",
  ],
};

const COLORS = {
  RESET: "\x1b[0m",
  BOLD: "\x1b[1m",
  GREEN: "\x1b[32m",
  YELLOW: "\x1b[33m",
  BLUE: "\x1b[34m",
  MAGENTA: "\x1b[35m",
  CYAN: "\x1b[36m",
  GRAY: "\x1b[90m",
  RED: "\x1b[31m",
};

module.exports = { actions, COLORS };